### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [libitx/txpost-js#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by libitx** [comment]
I dont use TS myself but I would be happy to see this.

However, this project is still a work in progress. I've not launched it yet. If you're looking for a project to contribute to maybe [TxForge](https://github.com/libitx/txforge) might have a better need for TS descriptions right now.

**Comment by geopic** [comment]
No problem @libitx, I'll close this issue then and work on the other library. If you want me to write one for this library, just open the issue back up :+1:
